version: '3'
services:
  web:
    build:
      context: .
      args:
        app_env: development
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/local/docker_test
      - bundle-data:/usr/local/bundle
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    tty: true
    stdin_open: true
    links:
      - postgres
  postgres:
    image: postgres:11.4
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  bundle-data: {}
  postgres-data: {}
